apiVersion: v1
kind: Service
metadata:
  annotations:
    service.spec.externalTrafficPolicy: Local
  name: {{ include "myip.fullname" . }}
  labels:
    {{- include "myip.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: flask-port
      protocol: TCP
      name: http
  selector:
    {{- include "myip.selectorLabels" . | nindent 4 }}
